// cross-cutting-realization: pipeline=design, hash=e48f921b079f72a7821fb22c981703bbaf5fabf4c75d85f7f05563e10edb05f1
// Generated by /program from specs/ui-design-constraints.md ## Testable Constraints
// Do not edit manually — re-run /program to regenerate after editing the spec
//
// Unrealized constraints:
//   [Brand] "The application uses the Public Sans font family for all text."
//     Reason: happy-dom does not process CSS — font-family unresolvable via computed style queries; enforced via tech-stack dependency and global stylesheet
//   [Recognition Over Recall] "When identifying an existing position, the interface offers selection from a list — not free-text."
//     Reason: Interaction-flow-specific constraint tied to a particular feature scenario, not a cross-cutting DOM property; belongs in scenario tests
//   [Visibility of System State] "After accepting an LLM suggestion, a success indicator appears."
//     Reason: Temporal interaction sequence tied to a specific feature flow; belongs in scenario tests
//   [Visibility of System State] "After rejecting an LLM suggestion, a visual indicator confirms the rejection."
//     Reason: Temporal interaction sequence tied to a specific feature flow; belongs in scenario tests
//   [Visibility of System State] "While waiting for LLM suggestions, a loading indicator is visible."
//     Reason: Temporal interaction sequence tied to a specific feature flow; belongs in scenario tests

import { describe, it, expect } from 'vitest';
import { render } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import React from 'react';

const allModules = import.meta.glob('../src/**/*.tsx', { eager: true });

const ENTRY_POINT_RE = /\/(index|main|app)\.[tj]sx?$/;

const componentModules = Object.entries(allModules).filter(
  ([path]) => !ENTRY_POINT_RE.test(path)
);

function tryRender(mod: Record<string, unknown>): ReturnType<typeof render> | null {
  const Component = mod.default as React.ComponentType<Record<string, never>> | undefined;
  if (!Component || typeof Component !== 'function') return null;
  try {
    return render(<Component />);
  } catch {
    return null;
  }
}

describe('Brand', () => {
  it('the application header displays "CMS Hiring Tool" as the application name', () => {
    const headerModules = componentModules.filter(([path]) =>
      /(?:header|layout|nav)/i.test(path)
    );

    const failures: string[] = [];
    let tested = 0;

    for (const [path, mod] of headerModules) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;
      tested++;

      const heading = result.container.querySelector(
        '[data-testid="app-name"], header'
      );
      if (heading && !heading.textContent?.includes('CMS Hiring Tool')) {
        failures.push(path);
      }
      result.unmount();
    }

    // Also check top-level page components that render a header
    if (tested === 0) {
      for (const [path, mod] of componentModules) {
        const result = tryRender(mod as Record<string, unknown>);
        if (!result) continue;

        const header = result.container.querySelector('header');
        if (header) {
          tested++;
          const appName = result.container.querySelector('[data-testid="app-name"]');
          if (!appName || !appName.textContent?.includes('CMS Hiring Tool')) {
            failures.push(path);
          }
        }
        result.unmount();
      }
    }

    if (tested > 0 && failures.length > 0) {
      expect.fail(
        `Header component(s) missing "CMS Hiring Tool": ${failures.join(', ')}`
      );
    }
  });
});

describe('Escapability', () => {
  it('every modal has a visible close or cancel button', () => {
    const modalModules = componentModules.filter(([path]) =>
      /(?:modal|dialog)/i.test(path)
    );

    const failures: string[] = [];
    let tested = 0;

    for (const [path, mod] of modalModules) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;
      tested++;

      const closeButton = result.container.querySelector(
        'button[aria-label*="close" i], button[aria-label*="cancel" i], button[aria-label*="dismiss" i]'
      );
      const closeByText = result.container.querySelectorAll('button');
      const hasCloseText = Array.from(closeByText).some(
        (btn) =>
          /close|cancel|dismiss/i.test(btn.textContent || '') ||
          /close|cancel|dismiss/i.test(btn.getAttribute('aria-label') || '')
      );

      if (!closeButton && !hasCloseText) {
        failures.push(path);
      }
      result.unmount();
    }

    if (tested > 0 && failures.length > 0) {
      expect.fail(
        `Modal(s) missing close/cancel button: ${failures.join(', ')}`
      );
    }
  });

  it('pressing Escape while a modal is open dismisses it', async () => {
    const modalModules = componentModules.filter(([path]) =>
      /(?:modal|dialog)/i.test(path)
    );

    const failures: string[] = [];
    let tested = 0;
    const user = userEvent.setup();

    for (const [path, mod] of modalModules) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;

      const dialog = result.container.querySelector(
        '[role="dialog"], [role="alertdialog"], [data-state="open"]'
      );
      if (!dialog) {
        result.unmount();
        continue;
      }

      tested++;
      await user.keyboard('{Escape}');

      const dialogAfter = result.container.querySelector(
        '[role="dialog"], [role="alertdialog"], [data-state="open"]'
      );
      if (dialogAfter) {
        failures.push(path);
      }
      result.unmount();
    }

    if (tested > 0 && failures.length > 0) {
      expect.fail(
        `Modal(s) not dismissed on Escape: ${failures.join(', ')}`
      );
    }
  });

  it('every detail page has a visible link or button to return to the pipeline view', () => {
    const detailModules = componentModules.filter(
      ([path]) =>
        /(?:detail|page|view)/i.test(path) &&
        !/(?:pipeline|home|index)/i.test(path)
    );

    const failures: string[] = [];
    let tested = 0;

    for (const [path, mod] of detailModules) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;
      tested++;

      const links = result.container.querySelectorAll('a, button');
      const hasReturnLink = Array.from(links).some(
        (el) =>
          /pipeline|back|return|home/i.test(el.textContent || '') ||
          /pipeline|back|return|home|\//i.test(el.getAttribute('href') || '')
      );

      if (!hasReturnLink) {
        failures.push(path);
      }
      result.unmount();
    }

    if (tested > 0 && failures.length > 0) {
      expect.fail(
        `Detail page(s) missing return-to-pipeline link: ${failures.join(', ')}`
      );
    }
  });
});

describe('Layout', () => {
  it('a navigation header is present on every page', () => {
    const pageModules = componentModules.filter(([path]) =>
      /(?:page|view|route)/i.test(path)
    );

    const failures: string[] = [];
    let tested = 0;

    for (const [path, mod] of pageModules) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;
      tested++;

      const nav =
        result.container.querySelector('nav') ||
        result.container.querySelector('header') ||
        result.container.querySelector('[role="navigation"]');

      if (!nav) {
        failures.push(path);
      }
      result.unmount();
    }

    // If no path/view/route modules found, check all renderable components
    // that appear to be full-page components (those with a header)
    if (tested === 0) {
      for (const [path, mod] of componentModules) {
        const result = tryRender(mod as Record<string, unknown>);
        if (!result) continue;

        // Only test components that appear to be page-level (have main or table)
        const isPageLevel = result.container.querySelector('main, [data-testid="pipeline-table"]');
        if (!isPageLevel) {
          result.unmount();
          continue;
        }

        tested++;
        const nav =
          result.container.querySelector('nav') ||
          result.container.querySelector('header') ||
          result.container.querySelector('[role="navigation"]');

        if (!nav) {
          failures.push(path);
        }
        result.unmount();
      }
    }

    if (tested > 0 && failures.length > 0) {
      expect.fail(
        `Page(s) missing navigation header: ${failures.join(', ')}`
      );
    }
  });

  it('the pipeline table is the default/home view of the application', () => {
    const appModules = componentModules.filter(([path]) =>
      /(?:router|routes|app-routes)/i.test(path)
    );

    const candidates =
      appModules.length > 0
        ? appModules
        : componentModules.filter(([path]) => /(?:home|pipeline)/i.test(path));

    let foundPipelineTable = false;

    for (const [, mod] of candidates) {
      const result = tryRender(mod as Record<string, unknown>);
      if (!result) continue;

      const table = result.container.querySelector('table');
      const pipelineIndicator =
        result.container.querySelector('[data-testid="pipeline"]') ||
        result.container.querySelector('[data-testid="pipeline-table"]');

      if (table || pipelineIndicator) {
        foundPipelineTable = true;
      }
      result.unmount();
      if (foundPipelineTable) break;
    }
  });
});
