// cross-cutting-realization: pipeline=tech-stack, hash=1247bdf9ce2bcb9eb65c2d23656976f6a3e2241692005ecabd99a40f656fd961
// Generated by /program from specs/tech-stack-recommendations.md ## Testable Constraints
// Do not edit manually — re-run /program to regenerate after editing the spec

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(__dirname, '..');

describe('Dependencies', () => {
  const packageJson = JSON.parse(
    readFileSync(resolve(webRoot, 'package.json'), 'utf-8')
  );
  const deps = packageJson.dependencies ?? {};
  const devDeps = packageJson.devDependencies ?? {};

  it('web/package.json includes @fontsource/public-sans', () => {
    const found =
      '@fontsource/public-sans' in deps || '@fontsource/public-sans' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json includes @uswds/uswds', () => {
    const found =
      '@uswds/uswds' in deps || '@uswds/uswds' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json includes @trussworks/react-uswds', () => {
    const found =
      '@trussworks/react-uswds' in deps || '@trussworks/react-uswds' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json includes @mdxeditor/editor', () => {
    const found =
      '@mdxeditor/editor' in deps || '@mdxeditor/editor' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json includes react-router-dom', () => {
    const found =
      'react-router-dom' in deps || 'react-router-dom' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json includes @aws-sdk/client-bedrock-runtime', () => {
    const found =
      '@aws-sdk/client-bedrock-runtime' in deps ||
      '@aws-sdk/client-bedrock-runtime' in devDeps;
    expect(found).toBe(true);
  });

  it('web/package.json does not include openai', () => {
    expect(deps).not.toHaveProperty('openai');
    expect(devDeps).not.toHaveProperty('openai');
  });

  it('web/package.json does not include next', () => {
    expect(deps).not.toHaveProperty('next');
    expect(devDeps).not.toHaveProperty('next');
  });

  it('web/package.json does not include prisma', () => {
    expect(deps).not.toHaveProperty('prisma');
    expect(devDeps).not.toHaveProperty('prisma');
  });

  it('web/package.json does not include @anthropic-ai/sdk', () => {
    expect(deps).not.toHaveProperty('@anthropic-ai/sdk');
    expect(devDeps).not.toHaveProperty('@anthropic-ai/sdk');
  });

  it('web/package.json does not include tailwindcss', () => {
    expect(deps).not.toHaveProperty('tailwindcss');
    expect(devDeps).not.toHaveProperty('tailwindcss');
  });

  it('web/package.json does not include @radix-ui/react-dialog', () => {
    expect(deps).not.toHaveProperty('@radix-ui/react-dialog');
    expect(devDeps).not.toHaveProperty('@radix-ui/react-dialog');
  });
});

describe('File Tree', () => {
  it('web/src/main.tsx imports @fontsource/public-sans', () => {
    const content = readFileSync(
      resolve(webRoot, 'src', 'main.tsx'),
      'utf-8'
    );
    expect(content).toMatch(/@fontsource\/public-sans/);
  });

  it('web/src/main.tsx imports @uswds/uswds/dist/css/uswds.min.css', () => {
    const content = readFileSync(
      resolve(webRoot, 'src', 'main.tsx'),
      'utf-8'
    );
    expect(content).toMatch(/@uswds\/uswds\/dist\/css\/uswds\.min\.css/);
  });
});
